on:
  workflow_call:
    inputs:
      python_version:
        required: false
        default: "3.14"
        type: string
      handler:
        required: true
        type: string
      requirements_path:
        required: true
        type: string
      shared_modules_path:
        required: true
        type: string
      lambda_code_path:
        required: true
        type: string
      function_name:
        required: true
        type: string
    secrets:
      role-to-assume:
        required: true
      aws-region:
        required: true

jobs:
  deploy-lambda-with-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python_version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Package lambda with dependencies
        run: |
          cd backend
          mkdir -p lambda_package
          cd lambda_package

          echo "Installing dependencies..."
          pip install -r ../${{ inputs.requirements_path }} -t .

          echo "Copying Lambda function..."
          cp ../${{ inputs.lambda_code_path }} .

          echo "Copying shared modules..."
          cp -r ../${{ inputs.shared_modules_path }} .

      - name: Deploy to AWS
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: ${{ inputs.function_name }}
          code-artifacts-dir: ./backend/lambda_package
          handler: ${{ inputs.handler }}
          runtime: python${{ inputs.python_version }}

      - name: Clean package
        if: always()
        run: rm -rf backend/lambda_package
