name: Deploy all AWS Lambda functions

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/**"

permissions:
  id-token: write # required for OIDC
  contents: read

jobs:
  deploy-spotify-login-lambda:
    uses: ./.github/workflows/deploy_lambda_with_dependencies.yml
    with:
      handler: spotify_login.lambda_handler
      shared_modules_path: shared
      lambda_code_path: lambda/auth/spotify_login.py
      function_name: melodiary-spotify-login
    secrets: inherit

  deploy-spotify-login-callback-lambda:
    uses: ./.github/workflows/deploy_lambda_with_dependencies.yml
    with:
      handler: spotify_callback.lambda_handler
      requirements_path: lambda/auth/spotify_callback_requirements.txt
      shared_modules_path: shared
      lambda_code_path: lambda/auth/spotify_callback.py
      function_name: melodiary-spotify-callback
    secrets: inherit

  deploy-spotify-fetch-library-lambda:
    uses: ./.github/workflows/deploy_lambda_with_dependencies.yml
    with:
      handler: fetch_library.lambda_handler
      requirements_path: lambda/service/spotify/fetch_library_requirements.txt
      shared_modules_path: shared
      lambda_code_path: lambda/service/spotify/fetch_library.py
      function_name: melodiary-fetch-spotify-library
    secrets: inherit

  deploy-library-lambda:
    uses: ./.github/workflows/deploy_lambda_with_dependencies.yml
    with:
      handler: library.lambda_handler
      requirements_path: lambda/service/library_requirements.txt
      shared_modules_path: shared
      lambda_code_path: lambda/service/library.py
      function_name: melodiary-library
    secrets: inherit
