name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/deploy_lambda.yml"

permissions:
  id-token: write # required for OIDC
  contents: read

jobs:
  deploy-spotify-login-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: melodiary-spotify-login
          code-artifacts-dir: ./backend/lambda/auth
          handler: spotify_login.lambda_handler
          runtime: python3.14

  deploy-spotify-login-callback-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Package lambda with dependencies
        run: |
          cd backend
          mkdir -p lambda_package
          cd lambda_package

          echo "Installing dependencies..."
          pip install -r ../lambda/auth/spotify_callback_requirements.txt -t .

          echo "Copying Lambda function..."
          cp ../lambda/auth/spotify_callback.py .

          echo "Copying shared modules..."
          cp -r ../shared .

      - name: Deploy to AWS
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: melodiary-spotify-callback
          code-artifacts-dir: ./backend/lambda_package
          handler: spotify_callback.lambda_handler
          runtime: python3.14

      - name: Clean package
        if: always()
        run: rm -rf backend/lambda_package
